[tool.poetry]
name = "gejm"
version = "0.1.0"
description = ""
authors = ["Michal Sojka <msojka@gohealth.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pygame = "^2.5.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
